# Generated by Django 4.0.2 on 2022-02-03 09:39

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2022, 2, 3, 15, 9, 15, 539337))),
            ],
        ),
    ]
